### ISSUE TITLE
Menu Arrow Icons Not Rendering

### ISSUE THREAD

**Issue by barthisius** [cseitz5/atom-windows-titlebar-edit#1]
For some reason in the replacement menu, the sub-menu listings print "keyboard_right_arrow" on the right-hand side instead of the actual arrow icon:
![keyboard_right_arrow](https://user-images.githubusercontent.com/7706977/102455913-030b8480-4006-11eb-8b0a-8f53e72b8641.png)

This is on a fresh install of Atom on Windows 10. Unfortunately, I don't know much about how these icons are supposed to be inserted, and have had trouble figuring out what might be going wrong. Any help would be appreciated.

**Comment by 3BD-R** [comment]
I tried it in linux it works well but same issue
![Screenshot from 2021-01-21 18-24-02](https://user-images.githubusercontent.com/33579200/105380636-cb9c8300-5c16-11eb-97c2-2fedb1fa9f09.png)

**Comment by cseitz** [comment]
I'll look into this. It's working fine on my machine, and honestly, I made this edit for personal use. I didn't expect anyone else to use it so I never did any testing beyond my own machine.

**Comment by cseitz** [comment]
Okay, looks like the font was loading from the original package I forked this from. I've added the font file and it should be all good now.

Go ahead and update, let me know how it goes.

**Comment by 3BD-R** [comment]
lol i came out with my own fix 
![Screenshot from 2021-01-22 00-37-49](https://user-images.githubusercontent.com/33579200/105421433-c35e3b00-5c4a-11eb-99be-6e3c97afa9d5.png)
![Screenshot from 2021-01-22 00-37-34](https://user-images.githubusercontent.com/33579200/105421452-ca854900-5c4a-11eb-8e11-f5e7b14d8c45.png)

**Comment by 3BD-R** [comment]
but your fixes works well in this issue

**Comment by dumstarboi** [comment]
Confirming the latest commit fixed it for me as well! Thanks for the update!
